name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: PraveenJP/Contactwee@v1.0.0 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "contactwee" #Must be unique in Heroku
          heroku_email: "praveen.josephmasilamani@outlook.com"
          usedocker: true