name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "contactwee"
          heroku_email: "roadizpraveen@gmail.com"
          buildpack: "https://github.com/PraveenJP/Contactwee.git"
          procfile: "web: npm start"
